default:
	./prettyPrinter

cat-error1:
	cat redwall/bad_program1.rwall

run-error1:
	./prettyPrinter redwall/bad_program1.rwall

cat-error2:
	cat redwall/bad_program2.rwall

run-error2:
	./prettyPrinter redwall/bad_program2.rwall
cat-error3:
	cat redwall/bad_program3.rwall

run-error3:
	./prettyPrinter redwall/bad_program3.rwall

cat-arrays:

run-arrays:

cat-conditionals:

run-conditionals:

cat-recursion:

run-recursion:

cat-iteration:

run-iteration:

cat-functions:

run-functions:

cat-dictionary:

run-dictionary:

cat-problem:

run-problem:

clean:
	rm -rf ./__pycache__